### ISSUE TITLE
Add support for Homie MQTT convention

### ISSUE THREAD

**Issue by qwandor** [gbaranski/houseflow#197]
I was thinking of writing a Google Home-centric smarthome platform in Rust myself, and this looks quite similar to what I had in mind (from what I can see so far, some documentation would be good!), but it looks like you're using a custom protocol over websockets to communicate between devices and the server. It would be useful to support a standard protocol that works with existing devices, and the one that I prefer is the [Homie convention](https://homieiot.github.io/), which defines a way to structure MQTT topics so devices can define their capabilities and be discovered automatically.

I already wrote a couple of Rust crates to handle this ([homie-controller](https://crates.io/crates/homie-controller) for the controller side that could be integrated into houseflow), which would do a fair bit of the work. We'd need to define how it maps to the Google Home API structure, or perhaps make it configurable.

I might be able to send a PR to add this, if you're interested and can help me understand the architecture a bit first.

**Comment by gbaranski** [comment]
> This makes authentication pretty simple; I just have Mosquitto configured to allow full access to all topics under a certain prefix to the matching user. (My setup is a bit more complex in that I have another user with read-only access for saving historical data, but there's still nothing terribly complicated.)

That can work too, but it is not as integrated as my solution is, suppose that you want to support Google Home, you'd need to copy all permission related stuff from your mosquito configuration to some other place from which server can read just to make accepting [SYNC intent](https://developers.google.com/assistant/smarthome/reference/intent/sync) possible.

> I'm not familiar with Docker, but I'm not sure why that would be required. Mosquitto is available in Debian (and I guess other MQTT brokers too), so it's pretty easy to install and configure as you like, on a Raspberry Pi or otherwise.

Configuration yes, but making custom plugins require compiling plugin as a shared library and then plugging it, it's fine if you do it only once, but if you want to reproduce it on other computers easily, its much more complicated.

My current setup includes a 15 year old laptop running Houseflow server, two ESP8266 modules working as a Gate and Garage in my family's home.

It's very simple now, but I'm still waiting for DHT22 modules from AliExpress to plug them to ESP8266 or a Raspberry Pi

> I'm fairly happy with most of this, but the annoying part is OpenHAB, which requires a lot of manual configuration, is quite heavyweight and annoying to install, and doesn't have any feasible way of supporting multiple users (i.e. providing a hosted services to my friends to use for their homes). 

Houseflow is designed to support many users and houses, I had in mind that maybe someday I'll be able to sell Houseflow device to someone.

> I'm not familiar with Matrix but I'll have a look, or if you are on Discord that might be easier.

Tell me your discord nickname and I'll reach you out.

**Comment by qwandor** [comment]
Sure, I'm qwandor#0264 on Discord.

**Comment by gbaranski** [comment]
Coming to the conclusion, I think Homie MQTT Convention won't fit with current architecture. Maybe it'll make more sense after #238 will be merged. I'm closing this issue for now.
